/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_alpha.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_systray.h"

/* Other patches */
#include "aspectresize.h"
#include "attachx.h"
#include "cfacts.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "decorationhints.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "exresize.h"
#include "fakefullscreenclient.h"
#include "focusdir.h"
#include "fullscreen.h"
#include "mpdcontrol.h"
#include "moveresize.h"
#include "movestack.h"
#include "pertag.h"
#include "placemouse.h"
#include "restartsig.h"
#include "roundedcorners.h"
#include "setborderpx.h"
#include "sticky.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "xkb.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_monocle.h"
#include "layout_tile.h"

