/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_alpha.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_systray.c"

/* Other patches */
#include "aspectresize.c"
#include "attachx.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "dragcfact.c"
#include "exresize.c"
#include "fakefullscreenclient.c"
#include "focusdir.c"
#include "fullscreen.c"
#include "mpdcontrol.c"
#include "moveresize.c"
#include "movestack.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "roundedcorners.c"
#include "setborderpx.c"
#include "sticky.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "xkb.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_monocle.c"
#include "layout_tile.c"

